version: '3.7'
services:

  front:
    container_name: "front"
    image: ${AUTHOR}/front:${VERSION}
    ports:
      - target: 5003
        published: 80
        protocol: tcp
    environment:
      DATABASE_URI: ${DATABASE_URI}
    deploy:
      replicas: 2
    build: ./front

  back:
    container_name: "back"
    image: ${AUTHOR}/back:${VERSION}
    build: ./back
    ports:
      - target: 5002
    deploy:
      replicas: 2

  stream:
    container_name: "stream"
    image: ${AUTHOR}/stream:${VERSION}
    build: ./stream
    ports:
      - target: 5000
    deploy:
      replicas: 2

  mathy:
    container_name: "mathy"
    image: ${AUTHOR}/mathy:${VERSION}
    build: ./mathy
    ports:
      - target: 5001
    deploy:
      replicas: 2

